baseURL = "https://vpshost.cc"
languageCode = "zh-CN"
title = "VPS Host"
theme = "maupassant"

[author]
  name = "飞雪无情"

[params]
  author = "Aming"
  subtitle = "域名、VPS介绍使用优惠等"
  keywords = ""
  description = ""

#######

[menu]
  [[menu.main]]
    identifier = "books"
    name = "新书"
    url = "/books/"
    weight = 2
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4

#######

[[params.links]]
  title = "Android Gradle权威指南"
  name = "Android Gradle权威指南"
  url = "http://yuedu.baidu.com/ebook/14a722970740be1e640e9a3e"
[[params.links]]
  title = "常用开发工具CDN镜像"
  name = "常用开发工具CDN镜像"
  url = "http://mirrors.flysnow.org/"

#######

