#LanguageCode = "zh-CN"
# theme = "learn"
# theme = "casper"
# post = filename / :title / slug / categories

baseurl = "https://vpshost.cc"
disablePathToLower = false
languageCode = "en-us"
title = "VPS"
theme = "y-bootie-docs"
copyright = "Copyright (c) 2018, VPS Host; All rights reserved."

[params]
description = "有关VPS的使用与介绍."
#withSitePosts  = true
searchDomain   = "vpshost.cc"
noCategoryLink = true
highlightStyle = "github"

[[menu.main]]
  name   = "指南"
  url    = "/categories/guide/"
  weight = 1

[[menu.main]]
  name   = "VPS"
  url    = "/categories/vps/"
  weight = 2

[[menu.main]]
  name   = "域名"
  url    = "/categories/domains/"
  weight = 3

[[menu.main]]
  name   = "归档"
  url    = "/index/"
  weight = 5
  
[[menu.main]]
  name   = "关于"
  url    = "/about/"
  weight = 9