# left-side user profile
avatar: //images.financialexpress.com/2016/08/channel-v-l.jpg # by default https://octodex.github.com/images/baracktocat.jpg
location:
email:
social:
  github:
  weibo:
  linkedin:

# navbar menu
menu:
 archives: true
 tags: true
 categories: true

rss_dir: atom.xml

# widget
ga: # google analytics tracking code UA-XXXXXXX-X
baidutongji: # baidutongji tracking code
duoshuo: # duoshuo username
disqus: vpshost
gsc: # google custom search code
